### ISSUE TITLE
add `maxItems`/`minItems` in TypeSet/TypeList fields with a single item

### ISSUE THREAD

**Issue by ocobleseqx** [equinix/terraform-provider-equinix#305]
Working on https://github.com/equinix/pulumi-equinix/issues/5 I found out that several of the resource attributes that are defined as typeSet or TypeList, but are intended to have a single item, don't have the `maxItems` (and/or `minItems`) property. This is not a problem in terraform, although it could lead to errors if someone tries to define them more than once. However, this is causing a problem in the generation of the Pulumi provider, since it renames these fields using the plural word and also affects the configuration, since it expects an array instead of an object. For example the `equinix_fabric_connection.redundancy` is a single object but there's no `maxItems` definition. 

https://github.com/equinix/terraform-provider-equinix/blob/bbdfbb828fc45ae3ae46ca1318f35bd43e64c61a/equinix/fabric_connection_schema.go#L816-L823

This ends up in Pulumi with a *redundancies* array field instead of a *redundancy* object 

```
resources:
  example:
    type: equinix:fabric:Connection
    properties:
      redundancies:
      - priority: PRIMARY
```
